lsst/ci_hsc_gen3

- bin/pipeline.sh
`pipeline.sh` script is modified to exercise saving of the quantum graph
to pickle file and reading it back for execution. This seems to be a
useful integration test for functionality that can be broken and other
tests not noticing it.
> DM-25113: Run pipetask in two steps

- tests/test_filterLabelFixups.py
See docstrings in the commit for why this test lives here instead of in obs_base, where most of the tested logic lives.
> DM-28583: Test that FitsExposureFormatter checks filters.

- tests/test_filterLabelFixups.py
If we run CI with disassembled composites we know that by definition
the filter label will be written correctly. This makes it hard to
force it to fail by faking a mismatch between data ID and filter
label.
If in the future such a mismatch could occur we would have to
change the FilterLabel formatter to do the same correction
as is done in ExposureFormatter.
> DM-29288: Skip filterlabel correction test if composite is disassembled

- SConstruct
- configs/butler-seed.yaml
Adds YAML config file used as default value for --butler-config SCons
option, this configures registry to use UUID datasets records manager.
> DM-29196: Use UUID datasets manager as default for ci_hsc_gen3

- pipelines/DRP.yaml
...now that it's enabled upstream in obs_subaru by default.
> DM-29750: Explicitly disable FGCM.

- .gitignore
- python/lsst/ci/hsc/gen3/tests/__init__.py
- python/lsst/ci/hsc/gen3/tests/_mock.py
- tests/test_calibrate.py
- tests/test_coadd_outputs.py
- tests/test_filterLabelFixups.py
- tests/test_schema.py
- tests/test_validate_outputs.py
Added simple helper methods to identify mock execution and updated unit
tests to use those methods. Also ran `isort` on few files that I touched.
> DM-34435: Add support for mock execution to new unit tests

- tests/test_validate_outputs.py
getURI is not reliable with disassembled composites and
it's better to ask the datastore directly whether it has the
artifact.
> DM-34455: Ask datastore whether the dataset exists

- tests/test_validate_outputs.py
The bug fix in the decorrelation afterburner for difference imaging results in a different (and lower) number of diaSources and diaObjects detected, causing one of the unit tests to fail. This PR reduces the minimum number of sources needed for those tests.
> DM-34364: Reduce minimum number of diaSources and diaObjects

- tests/test_validate_outputs.py
The task dimensions gained a skymap and can no longer
use the same label
> DM-33959: Rename writeSourceTable to writeRecalibratedSourceTable

- tests/test_filterLabelFixups.py
This PR removes references to `getFilterLabel` and similarly-named methods, replacing them with `getFilter` (etc.) methods backed by `FilterLabel`.
> DM-27177: Deprecate transitional getFilterLabel API

- tests/test_coadd_outputs.py
- tests/test_hips_outputs.py
- tests/test_validate_outputs.py
> DM-38210: Use butler.get() rather than deprecated getDirect()

- bin/pipeline.sh
Two special graph building scripts now require output collection name to resolve output references.
> DM-39031: Specify output run for graph building scripts

- bin/pipeline.sh
- tests/test_lookupFunction.py
This also updates `pipeline.sh` trap-EXIT command to delete all temporary files, there can only be one trap command per signal.
> DM-39122: Pass output run to `GraphBuilder.makeGraph` to suppress warnings

- resources/external_jointcal.yaml
`external_jointcal.yaml` dataset IDs were non-unique, which caused issues with always-resolved refs.
> DM-37704: Update dataset IDs in export file

- bin/pipeline.sh
When a task has band in its quantum dimensions but does not have band in the dimensions of any of its inputs, it will run over all bands known to any instrument unless those bands are constrained by the data query.  It was an accident of the old QG generation algorithm that this wasn't happening before (unrelated tasks in the same step were providing a band constraint, but the middleware now sees them as unrelated).
> DM-38498: Add band constraint to faro --data-query argument.

- tests/test_filterLabelFixups.py
Remove visit_system since it is no longer needed. Without day_obs the physical_filter and band are ignored.
> DM-42636: Add day_obs to data ID when standardizing

- ups/ci_hsc_gen3.table
> DM-45131: Remove log dependency

- tests/test_coadd_outputs.py
The mask plane dict may or may not be set correctly depending on what other tests have loaded already. Since the state is not controlled by the test and there is no easy way to control it remove the tests.
> DM-45458: Remove two tests that are unreliable

- bin/pipeline.sh
- tests/test_coadd_outputs.py
- tests/test_validate_outputs.py
> DM-44232: Update CI pipeline to use MakeDirectWarp

- SConstruct
This lets us keep using HSC/calib as the name of the calibration collection and hence avoid a lot of churn.
> DM-46297: override guards against unlabeled curated calibration collections

- tests/test_coadd_outputs.py
- tests/test_validate_outputs.py
With DM-49071 warps and coadds are now in nJy, so their PhotoCalibs ues the (essentially passthough) PhotoCalib(1.0). With this change the tests now check that that warp and coadd inputs are equal to PhotoCalib(1.0).
> DM-49071: replace deprecated check for PhotoCalibs

- tests/test_astrometryFail.py
The tests on other single-visit catalogs are plenty sufficient, and we probably want to move these tests in the direction of only paying attention to final outputs, not intermediates.
> DM-49372: Stop testing 'source' quantities.
